import { Field, Form, Formik } from 'formik';
import React, { Fragment } from 'react';
import * as Yup from 'yup';
import { FlapperSpinner } from "react-spinners-kit"
import visa from '../../assets/img/payment/visa.svg';
import master from '../../assets/img/payment/master.svg';
import amex from '../../assets/img/payment/amex.svg';
import mistro from '../../assets/img/payment/mistro.svg';
import appple from '../../assets/img/payment/appple.svg';
import gpay from '../../assets/img/payment/gpay.svg';
import amazonpay from '../../assets/img/payment/amazonpay.svg';
import admin_image from "../../assets/img/costic/customer-6.jpg";
import ReactPhoneInput from "react-phone-input-2";

const Security = (props) => {
    return (
        <Fragment>

            <div className="row">
                <div className="col-xl-4 col-md-4 offset-2">
                    <div className="">
                        <div className="ms-panel-header">
                    <h6>Security</h6>
                        </div>
                    <div className="ms-panel-body">
                        <h6>Password</h6>
                    </div>
                </div>
                </div>
                <div className="col-xl-6 col-md-12">
                    <div className="ms-panel ms-panel-fh">

                        <div className="ms-panel-body">
                            <div className="col-xl-12 col-md-12">
                                <p>You last changed your password 5 months ago. </p>


                                <a className="btn btn-primary" href="#">Change Your Password</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="col-xl-4 col-md-4 offset-2">
                    <div className="">
                        <div className="ms-panel-header">
                            <h6>Secondary email</h6>
                        </div>
                        <div className="ms-panel-body">
                            <h6>A secondary email can be used to restore access to your account. Security notifications are also sent to this email. </h6>
                        </div>
                    </div>
                </div>
                <div className="col-xl-6 col-md-12 ">
                    <div className="ms-panel ms-panel-fh">
                        <div className="ms-panel-header">
                            <h6>Secondary email</h6>
                        </div>
                         <div className="ms-panel-body">
                            <div className="col-xl-12 col-md-12">
                                <p>You do not have a secondary email.</p>
                                <a className="btn btn-primary" href="#">Add Secondary Email</a>
                            </div>
                        </div>

                    </div>
                </div>




                <div className="col-xl-4 col-md-4 offset-2">
                    <div className="">
                        <div className="ms-panel-header">
                            <h6>Two-step authentication</h6>
                        </div>
                        <div className="ms-panel-body">
                            <h6>After entering your password, verify your identity with a second authentication method. </h6>
                        </div>
                    </div>
                </div>
                <div className="col-xl-6 col-md-12 ">
                    <div className="ms-panel ms-panel-fh">
                        <div className="ms-panel-header">
                            <h6>Two-step authentication is <strong>off.</strong> </h6>
                        </div>
                        <div className="ms-panel-body">
                            <div className="col-xl-12 col-md-12">
                                <p>
                                    <h6 className="ui-subheading">How it works</h6>
                                    <p>When you log in to Shopify, you’ll need to: </p>
                                    <ol className="ui-content-list ui-content-list--type-number">
                                        <li className="ui-content-list__item">Enter your password</li>
                                        <li className="ui-content-list__item">Enter a code generated by a mobile app or
                                            an SMS text message
                                        </li>
                                    </ol>

                                </p>
                                <a className="btn btn-primary" href="#">Turn on two-step</a>
                            </div>
                        </div>

                    </div>
                </div>



                <div className="col-xl-4 col-md-4 offset-2">
                    <div className="">
                        <div className="ms-panel-header">
                            <h6>Devices</h6>
                        </div>
                        <div className="ms-panel-body">
                            <h6>You're currently logged in to Shopify on these devices. If you don't recognize a device, log out to keep your account secure. </h6>
                        </div>
                    </div>
                </div>
                <div className="col-xl-6 col-md-12">
                    <div className="ms-panel ms-panel-fh">
                        <div className="ms-panel-header">
                            <h6>Logged In</h6>
                        </div>
                        <div className="ms-panel-body">
                            <div className="col-xl-12 col-md-12">
                                <ul className="ms-followers ms-list ms-scrollable">
                                    <li className="ms-list-item media">
                                        <div className="media-body mt-1"><h6>Firefox On Windows</h6>
                                            <p className="fs-12">Oct 22, 2020, 1:39 pm</p>
                                            <p className="fs-12">Vadodara, Gujarat, India</p>
                                            </div>
                                        <button type="button" className="btn btn-success" name="button">Logout</button>
                                    </li>
                                    <li className="ms-list-item media">
                                        <div className="media-body mt-1"><h6>Firefox On Windows</h6>
                                            <p className="fs-12">Oct 22, 2020, 1:39 pm</p>
                                            <p className="fs-12">Vadodara, Gujarat, India</p>
                                        </div>
                                        <button type="button" className="btn btn-success" name="button">Logout</button>
                                    </li>

                                </ul>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </Fragment >
    )

}

export default Security